---
title: "Phylogeny"
author: "Camille"
date: "5/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Generate Plant Phylogenetic Distance Matrices}
library(ape)

tree <- ape::read.tree("~/Downloads/ALLMB.tre")
plant_dat <- read.csv("~/Documents/GitHub/NetworkAGB/network/mut_plants.csv")
plants <- plant_dat$Species

pruned.tree <- drop.tip(tree,tree$tip.label[-na.omit(match(plants, tree$tip.label))])
distance.matrix_species_level <- cophenetic.phylo(pruned.tree)
write.csv(distance.matrix_species_level, "~/Documents/GitHub/NetworkAGB/network/distance.matrix_species_level.csv")


antipruned.tree <- drop.tip(tree,tree$tip.label[na.omit(match(plants, tree$tip.label))])
species_level_plants <- as.data.frame(pruned.tree$tip.label)
colnames(species_level_plants) <- "Species"

library(tidyverse)

anti_plants <- anti_join(plant_dat,species_level_plants,  by="Species")
sort(anti_plants$Genus)


#Build the plant phylogeny at the genus level 

plant_traits_mut <- read.csv("~/Documents/GitHub/NetworkAGB/network/plant_traits_mut.csv")

plants_new <- plant_traits_mut %>%
  select(Species, Genus, Family)
colnames(plants_new) <- c("species", "genus", "family")

library(V.PhyloMaker)

g_tree <- phylo.maker(sp.list = plants_new, scenarios=c("S1", "S2", "S3"))

tree_genus <- g_tree$scenario.3
tree_genus$tip.label
pruned.tree_genus <- drop.tip(tree_genus,tree_genus$tip.label[-na.omit(match(plants, tree_genus$tip.label))])
distance.matrix_genus_level <- cophenetic.phylo(tree_genus)
write.csv(distance.matrix_genus_level, "~/Documents/GitHub/NetworkAGB/network/distance.matrix_genus_level.csv")

dim(distance.matrix_genus_level)
dim(distance.matrix_species_level)
```

```{r Animal Phylogenies}
library(RRphylo)

animal_traits <- read.csv("~/Documents/GitHub/NetworkAGB/network/animal_traits_mut.csv")

mammals <- animal_traits$Species[animal_traits$Taxa=="Mammal"]

mammal_tree <- ape::read.nexus("~/Documents/GitHub/NetworkAGB/mammal_tree/output.nex")
bird_tree <- ape::read.nexus("~/Documents/GitHub/NetworkAGB/bird_tree/output.nex")


mammal_tree[1]$tree_4808
plot(mammal_tree[1]$tree_4808)
bird_tree$tree_2960
  

mammal_tree_concensus <- consensus(mammal_tree, p=0.5)
distance.matrix_mammals <- cophenetic.phylo(mammal_tree_concensus)
dim(distance.matrix_mammals)
plot(mammal_tree_concensus)
bird_tree_concensus <- consensus(bird_tree, p=0.5)
plot(bird_tree_concensus)
distance.matrix_birds <- cophenetic.phylo(bird_tree_concensus)


mammal_species <- as.data.frame(rownames(as.data.frame(distance.matrix_mammals)))
colnames(mammal_species) <- "Species"

missing_animals <- anti_join( animal_traits,mammal_species, by="Species")

distance.matrix_mammals_df <- as.data.frame(distance.matrix_mammals)


rownames(distance.matrix_mammals_df)[12] <- "Allochrocebus_lhoesti"
colnames(distance.matrix_mammals_df)[12] <- "Allochrocebus_lhoesti"
rownames(distance.matrix_mammals_df)[15] <- "Procolobus_badius"
colnames(distance.matrix_mammals_df)[15] <- "Procolobus_badius"

write.csv(distance.matrix_mammals_df, "~/Documents/GitHub/NetworkAGB/network/distance.matrix_mammals_df.csv")

```


